name: CMake Build - Windows

on:
  # push:
  #   branches: [ "develop" ]
  pull_request:
    branches: [ "develop", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        config: [ Release ]
        cc: [ cl ]
        include:
          - os: windows-latest
            cc: cl
            cxx: cl

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            C:\\llvm
            C:\\vcpkg\\installed
          key: windows-cache

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          vcpkg install yaml-cpp

      - name: Install LLVM
        if: steps.cache.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.6/clang+llvm-21.1.6-x86_64-pc-windows-msvc.tar.xz"
          Invoke-WebRequest -Uri $url -OutFile llvm.tar.xz
          7z x llvm.tar.xz
          7z x llvm.tar
          Move-Item clang+llvm-21.1.6-x86_64-pc-windows-msvc C:\\llvm

      - name: Add LLVM to Path
        shell: bash
        run: echo "C:\\llvm\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Verify LLVM
        shell: pwsh
        run: llvm-config --version

      - name: Configure CMake
        shell: pwsh
        run: >
          cmake
          -S ${{ github.workspace }}
          -B ${{ github.workspace }}/build
          -DCMAKE_C_COMPILER=${{ matrix.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
          -DCMAKE_BUILD_TYPE=${{ matrix.config }}
          -DCMAKE_UNITY_BUILD=ON
          -DSILENCE=ON
          -DCMAKE_TOOLCHAIN_FILE="C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"

      - name: Build
        shell: pwsh
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config ${{ matrix.config }}
          --parallel
